<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="manambar-PC" ignored="3" name="formos2" tests="3" failures="1" timestamp="2020-03-17T14:28:36 EET" time="15.555" errors="0">
  <testcase name="c1" time="0.009" classname="tests.forms.ContactUsForm"/>
  <testcase name="c2" time="0.005" classname="tests.forms.ContactUsForm">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at tests.forms.ContactUsForm.c2(ContactUsForm.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- c2 -->
  <testcase name="r1" time="6.666" classname="tests.forms.RegisterForm"/>
  <testcase name="c3" time="0.0" classname="tests.forms.ContactUsForm">
    <ignored/>
  </testcase> <!-- c3 -->
  <testcase name="r3" time="0.0" classname="tests.forms.RegisterForm">
    <ignored/>
  </testcase> <!-- r3 -->
  <testcase name="r2" time="0.0" classname="tests.forms.RegisterForm">
    <ignored/>
  </testcase> <!-- r2 -->
</testsuite> <!-- formos2 -->
